services:
  timemachine:
    image: timemachine
    container_name: timemachine
    environment:
      - TIMEMACHINE_PASSWORD=YourPasswordHere
    volumes:
      - ./backup:/backup
    ports:
      - "548:548"
    network_mode: host
    restart: unless-stopped
