[supervisord]
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:dbus]
command=dbus-daemon --system --nofork
autostart=true
autorestart=true
stopsignal=TERM

[program:avahi]
command=avahi-daemon --no-chroot --no-drop-root
autostart=true
autorestart=true
stopsignal=TERM

[program:netatalk]
command=netatalk -d
autostart=true
autorestart=true
stopsignal=TERM
